listening-port=3478
external-ip=89.182.77.159
tls-listening-port=5349
min-port=49152
max-port=65535
fingerprint
lt-cred-mech
user=self:jAZ3Mm8d/d7wGHXjuWr+QE2TtfPiKmu86y/MFLxxzsk
realm=wiretrustee.com
cert=/etc/coturn/certs/cert.pem
pkey=/etc/coturn/private/privkey.pem
log-file=stdout
no-software-attribute
pidfile="/var/tmp/turnserver.pid"
no-cli
