name: 'onboarding-worflow'

env: 
    WORKING_DIR: ./03-projects 

on:
  pull_request:
    branches-ignore:
      - main
    types: [opened] #, synchronize, reopened]
    paths: 
      - "03-projects/requests/**"
  push:
    branches-ignore:
      - main
    paths: 
      - "03-projects/requests/**"
  workflow_dispatch: {}

jobs:
  pr-with-terraform:
    environment: dev
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.6   

      - name: Terraform Init
        env: 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: false
        run: | 
          terraform init -input=false 
          echo ""

      - name: Terraform Plan
        id: tf_plan
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform plan -no-color -input=false -compact-warnings -out=tfplan
          terraform show -no-color tfplan > tfplan.txt
          echo "Plan completed"

        continue-on-error: false

      - name: Read plan output
        id: read_plan
        run: |
          PLAN_CONTENT="$(sed -e 's/`/\\`/g' tfplan.txt | sed -e 's/\r$//' )"
          echo "plan<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Terraform plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #commit hash > version
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.read_plan.outputs.plan }}
            })
           